### ISSUE TITLE
Update GitHub actions to **build** and deploy, rather than just deploy 

### ISSUE THREAD

**Issue by jrsmth** [JRSmiffy/delaunay#11]
Needs a `npm run build --prefix ./app` step; possibly a separate GitHub action to be run before pages one that does a `[release] ...` commit...

https://jrsmiffy.atlassian.net/jira/software/projects/DEL/boards/3?selectedIssue=DEL-39

**Comment by jrsmth** [comment]
```
  "scripts": {
    ...
    "gh-build": "npm run build --base-href /"
  },
```

Consider adding some some of versioning in, akin to the npm release in delauntor

**Comment by JRSmiffy** [comment]
Probs worth adding some some of versioning in, akin to the npm release in delauntor...
