### ISSUE TITLE
Decrement the range slider when a point is deleted

### ISSUE THREAD

**Issue by jrsmth** [JRSmiffy/delaunay#4]
https://jrsmiffy.atlassian.net/jira/software/projects/DEL/boards/3?selectedIssue=DEL-32

**Comment by jrsmth** [comment]
@haydende - Can confirm the slider is decremented when a point is clicked. Looks good, apart from when a click occurs and it doesn't delete the point. Like you said, thats related to #2, but I think we could do some defensive coding around this to ensure that slider is decremented only if the point is being removed. What do you think?

**Comment by haydende** [comment]
@JRSmiffy Thanks for confirming. I will take a look at making this work defensively :)

**Comment by jrsmth** [comment]
Pull request merged, appears to be working smoothly so I'll close this issue. If we notice odd behaviours, we can open another ticket. Thanks Hayden 👍
