### ISSUE TITLE
Issue selecting the precise colour that you want

### ISSUE THREAD

**Issue by jrsmth** [JRSmiffy/delaunay#7]
https://jrsmiffy.atlassian.net/jira/software/projects/DEL/boards/3?selectedIssue=DEL-37

**Comment by jrsmth** [comment]
Looks to be an improvement in the colour selection. However, I will leave this ticket open as there are still some issues selecting the precise colour. @haydende

**Comment by haydende** [comment]
@JRSmiffy I'm not getting the up-to-date version of the app when going to https://jrsmiffy.github.io/delaunay/, so my changes aren't appearing there.

Could you also provide some examples of the incorrect behaviour, please?

**Comment by jrsmth** [comment]
Apologies, missed this comment - just realised that there's a step missing from the build process. When there is a commit to `master`, the GitHub action is run but there is no `npm run build --prefix ./app` and so the same `index.js` is being served without updates from `index.ts`. 🤦‍♂️ 😂

When working on this before, I was running the `npm run build` locally and committing the new `index.js`. Which you can do too atm but I will assign myself an issue to fix this automatic **build** and deploy (rather than just deploy) and fix over the weekend.

Thanks @haydende 👍

**Comment by jrsmth** [comment]
The latest version has been deployed and the colour selection looks good. Closing issue, cheers Hayden.
